make:
	(cd CrypterSimApp_0; make -f CrypterSimApp_0.mak)

clean:
	(cd CrypterSimApp_0; make clean -f CrypterSimApp_0.mak)

debug:
	(cd CrypterSimApp_0; make debug -f CrypterSimApp_0.mak)

profile:
	(cd CrypterSimApp_0; make profile -f CrypterSimApp_0.mak)