make:
	(cd CrypterSimApp_w_TLM_0; make -f CrypterSimApp_w_TLM_0.mak)

clean:
	(cd CrypterSimApp_w_TLM_0; make clean -f CrypterSimApp_w_TLM_0.mak)

debug:
	(cd CrypterSimApp_w_TLM_0; make debug -f CrypterSimApp_w_TLM_0.mak)

profile:
	(cd CrypterSimApp_w_TLM_0; make profile -f CrypterSimApp_w_TLM_0.mak)