# TCL File Generated by Component Editor 13.1.1
# Fri Oct 24 08:34:59 EEST 2014
# DO NOT MODIFY


# 
# axi_to_channel "axi_to_channel" v1.0
#  2014.10.24.08:34:59
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module axi_to_channel
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_to_channel
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Panu Sjövall"
set_module_property DISPLAY_NAME axi_to_channel
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi3_to_channel
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file axi3_to_channel.vhd VHDL PATH axi3_to_channel.vhd TOP_LEVEL_FILE
add_fileset_file pre_calk_pkg.vhd VHDL PATH pre_calk_pkg.vhd


# 
# parameters
# 
add_parameter slave_data_width_g INTEGER 32
set_parameter_property slave_data_width_g DEFAULT_VALUE 32
set_parameter_property slave_data_width_g DISPLAY_NAME slave_data_width_g
set_parameter_property slave_data_width_g TYPE INTEGER
set_parameter_property slave_data_width_g UNITS None
set_parameter_property slave_data_width_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property slave_data_width_g HDL_PARAMETER true
add_parameter slave_address_width_g INTEGER 8
set_parameter_property slave_address_width_g DEFAULT_VALUE 8
set_parameter_property slave_address_width_g DISPLAY_NAME slave_address_width_g
set_parameter_property slave_address_width_g TYPE INTEGER
set_parameter_property slave_address_width_g UNITS None
set_parameter_property slave_address_width_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property slave_address_width_g HDL_PARAMETER true
add_parameter slave_id_width_g INTEGER 12
set_parameter_property slave_id_width_g DEFAULT_VALUE 12
set_parameter_property slave_id_width_g DISPLAY_NAME slave_id_width_g
set_parameter_property slave_id_width_g TYPE INTEGER
set_parameter_property slave_id_width_g UNITS None
set_parameter_property slave_id_width_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property slave_id_width_g HDL_PARAMETER true
add_parameter channel_width_g INTEGER 8
set_parameter_property channel_width_g DEFAULT_VALUE 8
set_parameter_property channel_width_g DISPLAY_NAME channel_width_g
set_parameter_property channel_width_g TYPE INTEGER
set_parameter_property channel_width_g UNITS None
set_parameter_property channel_width_g ALLOWED_RANGES -2147483648:2147483647
set_parameter_property channel_width_g HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point altera_axi_slave
# 
add_interface altera_axi_slave axi end
set_interface_property altera_axi_slave associatedClock clock
set_interface_property altera_axi_slave associatedReset reset_sink
set_interface_property altera_axi_slave readAcceptanceCapability 1
set_interface_property altera_axi_slave writeAcceptanceCapability 1
set_interface_property altera_axi_slave combinedAcceptanceCapability 1
set_interface_property altera_axi_slave readDataReorderingDepth 1
set_interface_property altera_axi_slave bridgesToMaster ""
set_interface_property altera_axi_slave ENABLED true
set_interface_property altera_axi_slave EXPORT_OF ""
set_interface_property altera_axi_slave PORT_NAME_MAP ""
set_interface_property altera_axi_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi_slave axi_slave_awid awid Input slave_id_width_g
add_interface_port altera_axi_slave axi_slave_awaddr awaddr Input slave_address_width_g
add_interface_port altera_axi_slave axi_slave_awlen awlen Input 4
add_interface_port altera_axi_slave axi_slave_awsize awsize Input 3
add_interface_port altera_axi_slave axi_slave_awburst awburst Input 2
add_interface_port altera_axi_slave axi_slave_awlock awlock Input 2
add_interface_port altera_axi_slave axi_slave_awcache awcache Input 4
add_interface_port altera_axi_slave axi_slave_awprot awprot Input 3
add_interface_port altera_axi_slave axi_slave_awvalid awvalid Input 1
add_interface_port altera_axi_slave axi_slave_awready awready Output 1
add_interface_port altera_axi_slave axi_slave_wid wid Input slave_id_width_g
add_interface_port altera_axi_slave axi_slave_wdata wdata Input slave_data_width_g
add_interface_port altera_axi_slave axi_slave_wstrb wstrb Input slave_data_width_g/8
add_interface_port altera_axi_slave axi_slave_wlast wlast Input 1
add_interface_port altera_axi_slave axi_slave_wvalid wvalid Input 1
add_interface_port altera_axi_slave axi_slave_wready wready Output 1
add_interface_port altera_axi_slave axi_slave_bid bid Output slave_id_width_g
add_interface_port altera_axi_slave axi_slave_bresp bresp Output 2
add_interface_port altera_axi_slave axi_slave_bvalid bvalid Output 1
add_interface_port altera_axi_slave axi_slave_bready bready Input 1
add_interface_port altera_axi_slave axi_slave_arid arid Input slave_id_width_g
add_interface_port altera_axi_slave axi_slave_araddr araddr Input slave_address_width_g
add_interface_port altera_axi_slave axi_slave_arlen arlen Input 4
add_interface_port altera_axi_slave axi_slave_arsize arsize Input 3
add_interface_port altera_axi_slave axi_slave_arburst arburst Input 2
add_interface_port altera_axi_slave axi_slave_arlock arlock Input 2
add_interface_port altera_axi_slave axi_slave_arcache arcache Input 4
add_interface_port altera_axi_slave axi_slave_arprot arprot Input 3
add_interface_port altera_axi_slave axi_slave_arvalid arvalid Input 1
add_interface_port altera_axi_slave axi_slave_rid rid Output slave_id_width_g
add_interface_port altera_axi_slave axi_slave_rdata rdata Output slave_data_width_g
add_interface_port altera_axi_slave axi_slave_rresp rresp Output 2
add_interface_port altera_axi_slave axi_slave_rlast rlast Output 1
add_interface_port altera_axi_slave axi_slave_rvalid rvalid Output 1
add_interface_port altera_axi_slave axi_slave_rready rready Input 1
add_interface_port altera_axi_slave axi_slave_arready arready Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point channel
# 
add_interface channel conduit end
set_interface_property channel associatedClock clock
set_interface_property channel associatedReset reset_sink
set_interface_property channel ENABLED true
set_interface_property channel EXPORT_OF ""
set_interface_property channel PORT_NAME_MAP ""
set_interface_property channel CMSIS_SVD_VARIABLES ""
set_interface_property channel SVD_ADDRESS_GROUP ""

add_interface_port channel channel_vz export Input 1
add_interface_port channel channel_data export Output channel_width_g
add_interface_port channel channel_lz export Output 1

