make:
	(cd Kvazaar_0; make -f Kvazaar_0.mak)

clean:
	(cd Kvazaar_0; make clean -f Kvazaar_0.mak)

debug:
	(cd Kvazaar_0; make debug -f Kvazaar_0.mak)

profile:
	(cd Kvazaar_0; make profile -f Kvazaar_0.mak)