make:
	(cd ARM_FPGA_memory_benchmarker_0; make -f ARM_FPGA_memory_benchmarker_0.mak)

clean:
	(cd ARM_FPGA_memory_benchmarker_0; make clean -f ARM_FPGA_memory_benchmarker_0.mak)

debug:
	(cd ARM_FPGA_memory_benchmarker_0; make debug -f ARM_FPGA_memory_benchmarker_0.mak)

profile:
	(cd ARM_FPGA_memory_benchmarker_0; make profile -f ARM_FPGA_memory_benchmarker_0.mak)