make:
	(cd BlinkerApp_0; make -f BlinkerApp_0.mak)

clean:
	(cd BlinkerApp_0; make clean -f BlinkerApp_0.mak)

debug:
	(cd BlinkerApp_0; make debug -f BlinkerApp_0.mak)

profile:
	(cd BlinkerApp_0; make profile -f BlinkerApp_0.mak)